import { expect, test } from '@playwright/test';

test('native fullscreen preserves the animation and its playback controls', async ({ page }) => {
  await page.goto('/photosynthesis');
  const film = page.locator('.photo-film');
  await film.getByRole('slider').fill('360');
  await film.getByRole('button', { name: 'Fullscreen', exact: true }).click();
  await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(true);
  await expect(film.getByRole('slider')).toHaveValue('360');
  await film.getByRole('button', { name: 'In hydroponics', exact: true }).click();
  await expect(film.getByRole('button', { name: 'In hydroponics', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(film.getByRole('slider')).toHaveValue('360');
  await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(true);
  await film.getByRole('button', { name: 'Play', exact: true }).click();
  await expect(film.getByRole('button', { name: 'Pause', exact: true })).toBeVisible();
  await film.getByRole('button', { name: 'Pause', exact: true }).click();
  await film.getByRole('button', { name: 'Exit fullscreen', exact: true }).click();
  await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(false);
  await expect(film.getByRole('button', { name: 'Fullscreen', exact: true })).toBeFocused();
  const day = page.locator('.photo-day');
  await day.getByRole('button', { name: 'Fullscreen', exact: true }).click();
  await day.getByRole('slider', { name: 'Fullscreen hour timeline' }).fill('18');
  await day.getByRole('button', { name: 'In soil', exact: true }).click();
  await expect(day.getByRole('button', { name: 'In soil', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(true);
  await expect(day.getByRole('img')).toHaveAttribute('aria-label', /^18:00/);
  await day.getByRole('button', { name: 'Animate this hour' }).click();
  await expect(day.getByRole('button', { name: 'Pause day animation' })).toBeVisible();
  await day.getByRole('button', { name: 'Exit fullscreen', exact: true }).click();
  await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(false);
});

test('mobile fallback supports Indonesian controls, focus containment and Escape', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.addInitScript(() => { Object.defineProperty(Element.prototype, 'requestFullscreen', { value: undefined, configurable: true }); });
  await page.goto('/photosynthesis');
  await page.getByRole('button', { name: 'Bahasa Indonesia', exact: true }).click();
  const film = page.locator('.photo-film');
  await film.getByRole('button', { name: 'Layar penuh', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Animasi fotosintesis', exact: true });
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole('button', { name: 'Keluar layar penuh' })).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  await expect(dialog.getByRole('slider')).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(dialog.getByRole('button', { name: 'Keluar layar penuh' })).toBeFocused();
  await expect.poll(() => dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/photosynthesis-fullscreen-mobile.png' });
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(film.getByRole('button', { name: 'Layar penuh', exact: true })).toBeFocused();
  await page.setViewportSize({ width: 844, height: 390 });
  const day = page.locator('.photo-day');
  await day.getByRole('button', { name: 'Layar penuh', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Animasi 24 jam' })).toBeVisible();
  await day.getByRole('button', { name: 'Di hidroponik', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Animasi 24 jam' })).toBeVisible();
  await expect(day.getByRole('button', { name: 'Di hidroponik', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(day.getByRole('button', { name: 'Putar jam ini' })).toBeInViewport();
  await expect(day.getByRole('slider', { name: 'Linimasa jam layar penuh' })).toBeInViewport();
  await page.keyboard.press('Escape');
});
