import { useState } from 'react';
import { Droplets, Gauge, Thermometer, FlaskConical } from 'lucide-react';
import type { Crop, Method, Stage } from '../data/garden';
import { growingTargets, ppmRange, rangeText, solutionTemperature, targetSources, type PpmScale } from '../data/growingTargets';
import { useGarden } from '../state';
const scaleKey = 'grow-together:ppm-scale';
function savedScale(): PpmScale { try { return localStorage.getItem(scaleKey) === '700' ? 700 : 500; } catch { return 500; } }
export default function GrowingTargets({ crop, method, stage }: { crop: Crop; method: Method; stage?: Stage }) {
  const { state } = useGarden(); const language = state.language;
  const t = (en: string, id: string) => language === 'en' ? en : id;
  const [scale, setScale] = useState<PpmScale>(savedScale);
  const target = growingTargets[crop.id]; const hydro = method === 'hydro';
  const selectScale = (value: PpmScale) => { setScale(value); try { localStorage.setItem(scaleKey, String(value)); } catch { /* The displayed conversion remains usable without storage. */ } };
  const display = (value: readonly [number, number]) => rangeText(value, language);
  const early = stage === 'prepare' || stage === 'sow';
  return <section className={`growing-targets ${hydro ? '' : 'soil-targets'}`} aria-label={t('Growing targets', 'Acuan kondisi tanam')}>
    <div className="targets-heading"><div><span className="eyebrow">{t('KNOW YOUR GROWING CONDITIONS', 'KENALI KONDISI TANAM ANDA')}</span><h2>{t('A few numbers to grow by.', 'Angka acuan untuk tumbuh.')}</h2></div>{hydro && <div className="ppm-scale" role="group" aria-label={t('PPM meter scale', 'Skala meter PPM')}><span>{t('Meter scale', 'Skala meter')}</span>{([500, 700] as const).map(value => <button key={value} aria-pressed={scale === value} onClick={() => selectScale(value)}>PPM {value}</button>)}</div>}</div>
    <div className="target-grid">
      {hydro && <><div className="target-metric"><FlaskConical size={19}/><span>{t('Solution pH', 'pH larutan')}</span><strong data-testid="target-ph">{display(target.ph)}</strong><small>{t('Nutrient availability', 'Ketersediaan nutrisi')}</small></div><div className="target-metric"><Gauge size={19}/><span>{t('Nutrient strength', 'Kepekatan nutrisi')}</span><strong data-testid="target-ppm">{display(ppmRange(target.ec, scale))} <em>PPM</em></strong><small data-testid="target-ec">EC {display(target.ec)} mS/cm · {t('scale', 'skala')} {scale}</small></div></>}
      <div className="target-metric"><Thermometer size={19}/><span>{t('Preferred growing air', 'Suhu udara tumbuh')}</span><strong data-testid="target-air">{display(target.air)} <em>°C</em></strong><small>{t('Around the leaves, in shade', 'Di sekitar daun, terlindung matahari')}</small></div>
      {hydro && <div className="target-metric"><Droplets size={19}/><span>{t('Nutrient solution', 'Suhu larutan nutrisi')}</span><strong data-testid="target-solution">{display(solutionTemperature)} <em>°C</em></strong><small>{t('Shared hydroponic reference', 'Acuan hidroponik umum')}</small></div>}
    </div>
    <p className="target-scope">{hydro ? t('pH and EC/PPM refer to the mixed reservoir solution for established growth, across the supported systems. They are starting references, not guaranteed optima or fertilizer doses.', 'pH dan EC/PPM mengacu pada larutan tandon setelah dicampur untuk pertumbuhan tanaman mapan, pada sistem yang tersedia. Angka ini acuan awal, bukan jaminan optimum atau takaran pupuk.') : t('Air temperature applies to soil growing too. Hydroponic PPM and solution-pH targets do not measure soil fertility: test your soil or potting mix and use its fertilizer guidance.', 'Suhu udara juga berlaku untuk tanam di tanah. Target PPM dan pH larutan hidroponik tidak mengukur kesuburan tanah: uji tanah/media pot dan ikuti panduan pupuknya.')}</p>
    {hydro && early && <p className="target-stage-note">{t('At this step: do not apply the established-plant PPM target to ungerminated seeds. Moisten plugs as directed; once true leaves appear, follow your nutrient product’s seedling strength and increase gradually.', 'Pada langkah ini: jangan gunakan target PPM tanaman mapan untuk benih yang belum berkecambah. Lembapkan media sesuai petunjuk; setelah daun sejati muncul, ikuti kepekatan nutrisi bibit dari produk dan naikkan bertahap.')}</p>}
    <details className="target-details"><summary>{t('How to use these ranges & sources', 'Cara memakai kisaran & sumber acuan')}</summary>
      <p>{hydro ? target.note[language] : crop.climate[language]}</p>
      {hydro && <><p>{t('PPM is an estimate converted from EC, not a measurement of individual nutrients. PPM 500 = EC × 500; PPM 700 = EC × 700 (EC in mS/cm). Match your meter’s scale; if unknown, use its EC mode. The displayed range includes salts already in the source water.', 'PPM adalah perkiraan dari EC, bukan pengukuran setiap unsur nutrisi. PPM 500 = EC × 500; PPM 700 = EC × 700 (EC dalam mS/cm). Cocokkan skala meter; jika belum tahu, gunakan mode EC. Rentang yang ditampilkan termasuk garam yang sudah ada pada air baku.')}</p><p>{t('Calibrate meters as their manuals direct. Mix complete nutrients into water separately, stir, let readings settle, set EC, then check pH. Recheck daily and after top-ups. Never add concentrates directly to the roots. Preserve an established Kratky air gap when topping up.', 'Kalibrasi meter sesuai manualnya. Campur nutrisi lengkap ke air secara terpisah, aduk, tunggu bacaan stabil, atur EC, lalu periksa pH. Cek setiap hari dan setelah penambahan air. Jangan tuang konsentrat langsung ke akar. Pertahankan celah udara Kratky yang sudah terbentuk saat menambah air.')}</p><p>{t('The shared solution reference is rounded from 72–75 °F (22–24 °C), not a measured optimum for each crop. Measure inside the reservoir, not in the air. Shade and insulate the tank; check root health, circulation and aeration when the solution runs hot. Preferred air ranges are growing references, not germination or survival limits.', 'Acuan larutan umum dibulatkan dari 72–75 °F (22–24 °C), bukan hasil ukur optimum setiap tanaman. Ukur di dalam tandon, bukan udara. Naungi dan insulasi tandon; periksa kesehatan akar, sirkulasi dan aerasi saat larutan panas. Rentang udara adalah acuan pertumbuhan, bukan batas perkecambahan atau kelangsungan hidup.')}</p></>}
      <ul className="target-sources">{targetSources(crop.id, hydro).map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a></li>)}</ul>
    </details>
  </section>;
}
