import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Player, type PlayerRef } from '@remotion/player';
import { ArrowRight, Leaf } from 'lucide-react';
import PhotosynthesisDay from './PhotosynthesisDay';
import AnimationFullscreen from './AnimationFullscreen';
import { useGarden } from '../state';
import { PhotosynthesisFilm, chapters, filmTiming } from '../remotion/PhotosynthesisFilm';
import type { Method } from '../data/garden';
const jejakinSource = 'https://www.jejakin.com/id/blog/the-process-of-photosynthesis';
export default function Photosynthesis() {
  const { state } = useGarden();
  const [params, setParams] = useSearchParams();
  const method: Method = params.get('method') === 'hydro' ? 'hydro' : 'soil';
  const [chapter, setChapter] = useState(0);
  const [frame, setFrame] = useState(0);
  const [playing, setPlaying] = useState(false);
  const player = useRef<PlayerRef>(null);
  useEffect(() => {
    const current = player.current;
    const update = ({ detail }: { detail: { frame: number } }) => { setChapter(Math.min(3, Math.floor(detail.frame / 180))); setFrame(detail.frame); };
    const onPlay = () => setPlaying(true); const onPause = () => setPlaying(false);
    setPlaying(false);
    current?.addEventListener('frameupdate', update);
    current?.addEventListener('play', onPlay); current?.addEventListener('pause', onPause); current?.addEventListener('ended', onPause);
    return () => { current?.removeEventListener('frameupdate', update); current?.removeEventListener('play', onPlay); current?.removeEventListener('pause', onPause); current?.removeEventListener('ended', onPause); };
  }, [method, state.language]);
  const t = (en: string, id: string) => state.language === 'en' ? en : id;
  const notes = [
    t('Chlorophyll in the leaf’s chloroplasts captures light energy. Sunlight or a suitable grow light can provide it.', 'Klorofil dalam kloroplas daun menangkap energi cahaya. Matahari atau lampu tanam yang sesuai dapat menyediakannya.'),
    method === 'soil' ? t('Roots absorb water from moist soil. Water moves through the plant’s xylem to the leaves; roots also take up dissolved minerals.', 'Akar menyerap air dari tanah lembap. Air bergerak melalui xilem menuju daun; akar juga menyerap mineral terlarut.') : t('Roots absorb water from the nutrient solution. The same xylem pathway carries it to the leaves. A complete hydroponic fertilizer supplies minerals.', 'Akar menyerap air dari larutan nutrisi. Jalur xilem yang sama membawanya ke daun. Pupuk hidroponik lengkap menyediakan mineral.'),
    t('Carbon dioxide from the air enters through tiny leaf pores called stomata. These pores also regulate water loss.', 'Karbon dioksida dari udara masuk melalui pori kecil daun yang disebut stomata. Pori ini juga mengatur kehilangan air.'),
    t('Using light energy, the plant builds sugars from carbon dioxide and water, releasing oxygen. Sugars provide building material and fuel for respiration.', 'Dengan energi cahaya, tanaman membentuk gula dari karbon dioksida dan air, sambil melepas oksigen. Gula menyediakan bahan pembangun dan energi untuk respirasi.'),
  ];
  const seek = (index: number) => { player.current?.pause(); player.current?.seekTo(index * 180 + 45); setChapter(index); };
  return <article className="photosynthesis-page page-width">
    <Link className="text-link" to="/how-it-works">{t('Learning essentials', 'Dasar belajar')}</Link>
    <header className="photo-heading"><div className="eyebrow">{t('A LITTLE SCIENCE FOR YOUR GARDEN', 'SEDIKIT SAINS UNTUK KEBUN ANDA')}</div><h1>{t('How a leaf makes food.', 'Cara daun membuat makanan.')}</h1><p>{t('One remarkable process. Two ways to grow. See how photosynthesis powers your plant, in soil and in hydroponics.', 'Satu proses menakjubkan. Dua cara menanam. Lihat bagaimana fotosintesis mendukung tanaman, di tanah maupun hidroponik.')}</p><p className="photo-attribution">{t('Photosynthesis explanation adapted from', 'Penjelasan fotosintesis dirangkum dari')} <a href={jejakinSource} target="_blank" rel="noreferrer">Jejakin · Fotosintesis: Proses Tumbuhan Menghasilkan Oksigen</a>.</p></header>
    <div className="photo-layout"><section className="photo-film" aria-label={t('Photosynthesis motion graphic', 'Animasi fotosintesis')}>

      <AnimationFullscreen aspectRatio={filmTiming.width / filmTiming.height} language={state.language} label={t('Photosynthesis animation', 'Animasi fotosintesis')}><div className="photo-methods" role="group" aria-label={t('Compare growing methods', 'Bandingkan metode tanam')}>{(['soil', 'hydro'] as const).map(m => <button key={m} aria-pressed={method === m} onClick={() => { player.current?.pause(); setParams({ method: m }, { preventScrollReset: true }); }}>{m === 'soil' ? t('In soil', 'Di tanah') : t('In hydroponics', 'Di hidroponik')}</button>)}</div><div className="animation-focus-stage"><Player key={`${method}-${state.language}`} ref={player} component={PhotosynthesisFilm} inputProps={{ language: state.language, method }} durationInFrames={filmTiming.durationInFrames} fps={filmTiming.fps} compositionWidth={filmTiming.width} compositionHeight={filmTiming.height} style={{ width: '100%' }} controls={false} clickToPlay={false} autoPlay={false} loop={false} showVolumeControls={false} moveToBeginningWhenEnded={false} initialFrame={frame} aria-label={t('Play photosynthesis animation', 'Putar animasi fotosintesis')} errorFallback={() => <p>{t('The animation could not load. Follow the four illustrated steps below.', 'Animasi tidak dapat dimuat. Ikuti empat langkah di bawah.')}</p>}/>
      </div><div className="photo-playback"><button onClick={() => { if (player.current?.isPlaying()) player.current.pause(); else { if (frame >= 719) player.current?.seekTo(0); player.current?.play(); } }}>{playing ? t('Pause', 'Jeda') : t('Play', 'Putar')}</button><input type="range" min={0} max={719} value={frame} aria-label={t('Animation timeline', 'Linimasa animasi')} aria-valuetext={`${Math.floor(frame / 30)} / 24 ${t('seconds', 'detik')}`} onChange={event => { player.current?.pause(); player.current?.seekTo(Number(event.target.value)); }}/><span>{Math.floor(frame / 30)} / 24 {t('s', 'dtk')}</span></div>
      <p className="photo-film-note">{t('24-second animation · press play, or select a step to explore a still. No audio is needed.', 'Animasi 24 detik · tekan putar, atau pilih langkah untuk melihat gambar diam. Tidak memerlukan audio.')}</p>
    </AnimationFullscreen></section><section className="photo-chapters" aria-label={t('Animation steps', 'Langkah animasi')}><div className="eyebrow">{t('FOLLOW THE JOURNEY', 'IKUTI PERJALANANNYA')}</div>{chapters.map((item, i) => <div className="photo-chapter" key={i}><button aria-pressed={chapter === i} onClick={() => seek(i)}><span>0{i + 1}</span>{item[state.language]}</button><p>{notes[i]}</p></div>)}</section></div>
    <PhotosynthesisDay language={state.language} method={method} onMethodChange={next => { player.current?.pause(); setParams({ method: next }, { preventScrollReset: true }); }}/>
    <section className="photo-process" aria-labelledby="photo-process-title"><div className="eyebrow">{t('INSIDE THE CHLOROPLAST', 'DI DALAM KLOROPLAS')}</div><h2 id="photo-process-title">{t('Two stages that work together.', 'Dua tahap yang saling melengkapi.')}</h2><p>{t('Photosynthesis stores light energy in sugars and releases oxygen. Jejakin introduces two linked stages inside chloroplasts.', 'Fotosintesis menyimpan energi cahaya dalam gula dan melepaskan oksigen. Jejakin menjelaskan dua tahap yang terhubung di dalam kloroplas.')}</p><div className="photo-process-stages"><div><h3>{t('01 · Light-dependent reactions', '01 · Reaksi terang')}</h3><p>{t('In thylakoid membranes, light drives water splitting, releasing oxygen. ATP and NADPH carry energy to the next stage.', 'Di membran tilakoid, cahaya mendorong pemecahan air yang melepaskan oksigen. ATP dan NADPH membawa energi ke tahap berikutnya.')}</p></div><div><h3>{t('02 · Calvin cycle', '02 · Siklus Calvin')}</h3><p>{t('In the stroma, ATP and NADPH help incorporate carbon dioxide into molecules used to build sugars.', 'Di stroma, ATP dan NADPH membantu mengolah karbon dioksida menjadi molekul bahan pembentuk gula.')}</p><p>{t('Sometimes called “dark reactions”, this stage does not require darkness. It relies on the products of the light reactions; G3P is an intermediate used to build sugars.', 'Kadang disebut “reaksi gelap”, tahap ini tidak harus berlangsung dalam gelap. Prosesnya bergantung pada hasil reaksi terang; G3P adalah zat antara untuk membentuk gula.')}</p></div></div><p className="photo-process-factors"><strong>{t('What affects the process?', 'Apa yang memengaruhi prosesnya?')}</strong> {t('Jejakin highlights light, carbon dioxide, water, and temperature. Both growing methods need suitable conditions.', 'Jejakin menyoroti cahaya, karbon dioksida, air, dan suhu. Kedua metode tanam memerlukan kondisi yang sesuai.')}</p><p className="photo-process-source">{t('Main reference:', 'Rujukan utama:')} <a href={jejakinSource} target="_blank" rel="noreferrer">{t('Jejakin’s photosynthesis article', 'Artikel fotosintesis Jejakin')}</a>. {t('Calvin cycle clarification:', 'Penjelasan tambahan siklus Calvin:')} <a href="https://openstax.org/books/biology-2e/pages/8-3-using-light-energy-to-make-organic-molecules" target="_blank" rel="noreferrer">OpenStax Biology 2e</a>.</p></section>
    <section className="photo-equation"><Leaf size={24}/><div><h2>{t('The same recipe, above the roots.', 'Resep yang sama, di atas akar.')}</h2><p className="photo-recipe">{t('Light + water + carbon dioxide → sugars + oxygen', 'Cahaya + air + karbon dioksida → gula + oksigen')}</p><p>{t('Light supplies energy; water and carbon dioxide supply the ingredients. Minerals support healthy leaves and metabolism, but fertilizer does not replace the sugar a plant makes.', 'Cahaya menyediakan energi; air dan karbon dioksida menyediakan bahan. Mineral mendukung kesehatan daun dan metabolisme, tetapi pupuk tidak menggantikan gula yang dibuat tanaman.')}</p><details><summary>{t('See the simplified chemical equation', 'Lihat persamaan kimia sederhana')}</summary><p>6 CO₂ + 6 H₂O → C₆H₁₂O₆ + 6 O₂ <span>({t('with light and chlorophyll', 'dengan cahaya dan klorofil')})</span></p><p>{t('This summarizes the overall process, which involves several reactions inside chloroplasts.', 'Ini merangkum proses keseluruhan yang melibatkan beberapa reaksi di dalam kloroplas.')}</p></details></div></section>
    <section className="photo-compare"><h2>{t('What changes below the surface?', 'Apa yang berbeda di bawah permukaan?')}</h2><div className="photo-table-wrap"><table><caption>{t('Soil and hydroponics: same leaf process, different root environment', 'Tanah dan hidroponik: proses daun sama, lingkungan akar berbeda')}</caption><thead><tr><th scope="col">{t('Plant need', 'Kebutuhan tanaman')}</th><th scope="col">{t('Soil', 'Tanah')}</th><th scope="col">{t('Hydroponics', 'Hidroponik')}</th></tr></thead><tbody>{[
      [t('Water', 'Air'), t('Held in moist soil; avoid prolonged waterlogging.', 'Tersimpan di tanah lembap; hindari genangan berkepanjangan.'), t('Supplied by nutrient solution; keep the system’s working level.', 'Disediakan larutan nutrisi; jaga tinggi kerja sistem.')],
      [t('Minerals', 'Mineral'), t('Dissolved in soil water, from soil reserves and amendments.', 'Terlarut dalam air tanah, dari cadangan tanah dan bahan tambahan.'), t('Added through complete hydroponic nutrients; check pH and EC.', 'Ditambahkan melalui nutrisi hidroponik lengkap; periksa pH dan EC.')],
      [t('Root oxygen', 'Oksigen akar'), t('Air spaces in well-drained soil support root respiration.', 'Ruang udara di tanah berdrainase baik mendukung respirasi akar.'), t('Aeration or an air-root zone, depending on the system.', 'Aerasi atau zona akar udara, sesuai sistemnya.')],
      [t('Light and CO₂', 'Cahaya dan CO₂'), t('Leaves receive light and exchange gases with the air.', 'Daun menerima cahaya dan bertukar gas dengan udara.'), t('The same needs: growing without soil does not remove them.', 'Kebutuhan sama: menanam tanpa tanah tidak menghilangkannya.')],
    ].map(([need, soil, hydro]) => <tr key={need}><th scope="row">{need}</th><td>{soil}</td><td>{hydro}</td></tr>)}</tbody></table></div></section>
    <section className="photo-practice"><h2>{t('Help your leaves do their work.', 'Bantu daun menjalankan tugasnya.')}</h2><p>{t('Give each crop suitable light, reliable water, enough space, and healthy roots. In tropical heat, use the crop’s shade and temperature guidance; more sun is not always better. Keep roots supplied with oxygen: photosynthesis releasing oxygen in leaves does not replace root aeration. Plants also respire day and night.', 'Berikan cahaya sesuai tanaman, air yang cukup, ruang tumbuh, dan akar sehat. Saat panas tropis, ikuti panduan naungan dan suhu tanaman; lebih banyak matahari tidak selalu lebih baik. Pastikan akar mendapat oksigen: oksigen dari fotosintesis di daun tidak menggantikan aerasi akar. Tanaman juga berespirasi siang dan malam.')}</p><Link className="text-link" to="/plants">{t('Choose a plant to try it', 'Pilih tanaman untuk mencobanya')}<ArrowRight size={16}/></Link></section>
    <section className="photo-sources"><h2>{t('Sources and further reading', 'Sumber dan bacaan lanjutan')}</h2><p>{t('The general photosynthesis explanation follows Jejakin. The soil and hydroponics comparison uses the additional gardening references below.', 'Penjelasan umum fotosintesis merujuk Jejakin. Perbandingan tanah dan hidroponik menggunakan rujukan berkebun tambahan di bawah.')}</p><a href={jejakinSource} target="_blank" rel="noreferrer">Jejakin · Fotosintesis: Proses Tumbuhan Menghasilkan Oksigen</a><a href="https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/lighting-for-indoor-plants" target="_blank" rel="noreferrer">University of Minnesota Extension · {t('Light and photosynthesis', 'Cahaya dan fotosintesis')}</a><a href="https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/small-scale-hydroponics" target="_blank" rel="noreferrer">University of Minnesota Extension · {t('Small-scale hydroponics', 'Hidroponik skala kecil')}</a><a href="https://open.lib.umn.edu/horticulture/part/chapter-11-water-and-light/" target="_blank" rel="noreferrer">The Science of Plants · {t('Water and light', 'Air dan cahaya')}</a></section>
  </article>;
}
