import { Check, ChevronDown, Droplets, Info, Zap, ZapOff } from 'lucide-react';
import type { Crop } from '../data/garden';
import { initialSystem, hydroSystems, systemSupport, type HydroSystemId } from '../data/hydroSystems';
import { useGarden } from '../state';
import HydroDiagram from './HydroDiagram';
export default function SystemPicker({ crop, selected, onSelect, compact = false }: { crop: Crop; selected: HydroSystemId; onSelect: (system: HydroSystemId) => void; compact?: boolean }) {
  const { state } = useGarden(); const language = state.language; const t = (en: string, id: string) => language === 'en' ? en : id;
  const system = hydroSystems.find(s => s.id === selected)!;
  if (compact) return <section className="lesson-system"><div className="system-select-wrap"><Droplets size={18}/><label htmlFor="lesson-system-select">{t('Hydroponic system', 'Sistem hidroponik')}</label><select id="lesson-system-select" value={selected} onChange={e => onSelect(e.target.value as HydroSystemId)}>{hydroSystems.map(s => <option key={s.id} value={s.id} disabled={!systemSupport(crop, s.id).available}>{s.name[language]}{!systemSupport(crop, s.id).available ? t(' · other crops', ' · tanaman lain') : ''}</option>)}</select><ChevronDown size={14}/></div><p>{system.description[language]}</p><details><summary>{t('System essentials & cautions', 'Kebutuhan & perhatian sistem')}</summary><p><strong>{system.power[language]}</strong> · {system.caution[language]}</p></details></section>;
  return <section id="hydro-systems" className="system-picker"><div className="system-picker-title"><div className="eyebrow">{t('SIX SYSTEMS, DIFFERENT WAYS TO GROW', 'ENAM SISTEM, BERAGAM CARA MENANAM')}</div><h2>{t('Find your kind of hydroponics.', 'Temukan sistem hidroponik Anda.')}</h2><p>{t('Compare how nutrients reach the roots, what needs power, and what fits this crop.', 'Bandingkan cara nutrisi mencapai akar, kebutuhan listrik, dan kecocokan untuk tanaman ini.')}</p></div><div className="system-grid" aria-label={t('Choose hydroponic system', 'Pilih sistem hidroponik')}>{hydroSystems.map(s => { const support = systemSupport(crop, s.id); const chosen = selected === s.id; const passive = ['wick', 'kratky'].includes(s.id); return <article className={`system-card ${chosen ? 'selected' : ''} ${support.available ? '' : 'unavailable'}`} key={s.id}><button className="system-card-choice" aria-pressed={chosen} disabled={!support.available} onClick={() => onSelect(s.id)} aria-label={`${t('Choose', 'Pilih')} ${s.name[language]}`}><div className="system-card-top"><span>{s.name[language]}</span>{chosen ? <span className="system-check"><Check size={14}/></span> : s.id === initialSystem(crop) ? <span className="system-recommended">{t('Recommended', 'Disarankan')}</span> : null}</div><HydroDiagram crop={crop} systemId={s.id} stage="care" language={language} thumbnail/><strong className="system-full-name">{s.fullName[language]}</strong><p>{s.description[language]}</p><div className="system-power">{passive ? <ZapOff size={13}/> : <Zap size={13}/>}<span>{s.power[language]}</span></div></button><p className="system-support-note">{support.available ? s.difficulty[language] : support.note[language]}</p></article>; })}</div><div className="system-detail" role="status"><div><span className="eyebrow">{system.name[language]} · {t('YOUR SELECTED SYSTEM', 'SISTEM PILIHAN ANDA')}</span><h3>{system.fullName[language]}</h3><p>{system.advantage[language]}</p></div><div className="system-caution"><Info size={18}/><p>{system.caution[language]}</p></div></div></section>;
}
